server:
  port: 8080
  tomcat:
    max-swallow-size: 10MB
    max-http-form-post-size: 10MB
spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 10MB
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**,/customer/api/v1/customer/register
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/v1/hotel/**
          filters:
            - StripPrefix=1
      default-filters:
        - AuthFilter




  #This is for config client
 # config:
  #  import: optional:configserver:http://localhost:8762

#This is for eureka client
eureka:
  client:
    register-with-eureka: true #default
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true #deafult
# This is for spring activator (we can check mapping and health more... for microservice architecture)
management:
  endpoints:
    web:
      exposure:
        include: "*"
